### ISSUE TITLE
Javascript port of CSG part

### ISSUE THREAD

**Issue by hrgdavor** [bluelightning32/walnut#1]
Hi, what would be the part of the code that does CSG operations ?

what representation of meshes is used ?
 - 3 point vertex
 - 4 planes intersection 

https://arxiv.org/pdf/2103.02486.pdf

this topic very much interests me :)

**Comment by hrgdavor** [comment]
Any hints how to run your code on Windows. Also, would you consider generating WASM ?

**Comment by bluelightning32** [comment]
We're working together on a WebAssembly interface to Walnut at https://github.com/bluelightning32/walnut-javascript.

The discussion is happening in the walnut internals thread at https://discord.gg/UXtQcA6.
