### ISSUE TITLE
Request -Native Windows support (multi platform) 

### ISSUE THREAD

**Issue by yetigit** [bluelightning32/walnut#7]
Alot of the things behind the exact arithmetic classes use assumptions you would make under unix / posix systems.
Compile dump of the generated project under visual studio  :
https://pastebin.com/YEgs4yTy

**Comment by bluelightning32** [comment]
Yeah, you found out that I develop in Linux :)

I have access to a Windows laptop. I'll install Visual Studio Community Edition on it and try to fix it. Can you tell me more about how you plan to use Walnut? Do you need the VTK parts?

**Comment by yetigit** [comment]
> Yeah, you found out that I develop in Linux :)
> 
> 
> 
> I have access to a Windows laptop. I'll install Visual Studio Community Edition on it and try to fix it. Can you tell me more about how you plan to use Walnut? Do you need the VTK parts?

I disabled the vtk part on cmake, need to possibly use walnut w my own mesh processing stuff

**Comment by bluelightning32** [comment]
See if the change I pushed fixes it for you. I'm going to keep the issue open a little longer to update the documentation and see if I can get VTK to work too.
