### ISSUE TITLE
vs2015 compile error related question

### ISSUE THREAD

**Issue by qweret123** [bluelightning32/walnut#8]
Is there any way to build walnut in vs2015? 

C3249: illegal statement or sub-expression for 'constexpr' function occurs in big_uint_word.h

**Comment by bluelightning32** [comment]
Walnut is written in C++14. It appears that vs2015 does not work because it does not have full C++14 support for constexpr.

The missing feature is listed as "extended constexpr" on https://devblogs.microsoft.com/cppblog/c111417-features-in-vs-2015-rtm/.
